### ISSUE TITLE
misspelled css property value on some spacing utils

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/elements#118]
**Describe the bug**
Using the incorrect css variable on some spacing utils on 5.0.0-beta.9

utils variable that affected:
- elM4
- elMl4
- elMr4
- elMb4
- elMt4
- elMy4
- elMx4
- elP4
- elPr4
- elPl4
- elPy4
- elPx4
- elPt4
- elPb4

https://github.com/reapit/elements/blob/main/src/styles/spacing.ts

![image](https://github.com/reapit/elements/assets/96416644/dc1441f5-45fa-43db-a12a-0eabdee0ddc2)

**Comment by jmsfwk** [comment]
@adrian-reapit Is there going to be a patch version released with this fix?
