### ISSUE TITLE
addSnackWithTimeout is not a function when built

### ISSUE THREAD

**Issue by bashleigh** [reapit/elements#126]
**Describe the bug**
When the elements package is built and deployed to admin-portal, I've found a bug where `addSnackWithTimeout` var within `useSnack` is not a function. The exception itself, because the package is minified: `l is not a function`. I tracked this back to `addSnackWithTimeout` (see screenshots). I then checked the elements package and my IED is suggesting that `addSnackWithTimeout` should be defined using `useMemo` as the value will not always be a function. Putting two and two together I reckon this is our issue.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://admin-portal.dev.paas.reapit.cloud
2. log in etc
3. open the expandable content
4. click enable/disable toggle
5. notice the snack notification is not present
6. with the current deployment to admin-portal dev, I've removed the catch block from `useReapitUpdate` which should now console.error the error to the console

**Expected behaviour**
Snack notification should show

**Screenshots**

<img width="607" alt="Screenshot 2024-07-01 at 09 52 09" src="https://github.com/reapit/elements/assets/11574250/4c7f2de9-aaf6-4fad-958c-4b0a22f41aec">
<img width="599" alt="Screenshot 2024-07-01 at 09 52 04" src="https://github.com/reapit/elements/assets/11574250/b7f180c0-1564-489a-b4e6-4aa120213929">

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac] 
 - Browser [e.g. Chrome, Safari] chrome
 - Version [e.g. 22] ^5.0.0-beta.7

**Additional context**

**Comment by willmcvay** [comment]
This is not an Elements bug - the issue is that useReapitData is using the snack in v4 of Elements, whereas the Admin Portal is using the v5 beta. We should be migrating the whole of Foundations to the v5 beta ASAP but in the short term, we can revert to v4 in admin.
