### ISSUE TITLE
v5 component refactor: TextArea

### ISSUE THREAD

**Issue by kurtdoherty** [reapit/elements#136]
**Abstract**

_As part of the v5 Elements release, each component will be reviewed and refactored to ensure best practice and design system alignment_.

The existing `TextArea` component in Elements does not currently meet all aspects of the Design System's TextArea specification.

**Specification**

- Is new component or existing? **Existing**
- Is the component being re-named? **No**
- Is the component design signed off by product and design? **Unknown**
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to DS in Figma](https://www.figma.com/design/6CaivqdlTX0UkFYJkpBKDu/Reapit-DS?node-id=428-9227&t=3FvWMbhNKUniX3TP-4)
- [Link to Elements Audit in Figma](https://www.figma.com/design/J6EneNGfpk2GcUuymiOKW4/Elements-Gaps-%2B-Discrepancies?node-id=319-6548&t=rBEuqtRqTtxyBUpo-4)
- Additional behavioural specification: **Not available yet**
- Accessibility requirements: **Not applicable, because we're using the standard `<textarea>` HTML element**

**Developer Checklist**

- [x] Styles alignment between Design System and Elements
- [x] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [x] Align with accessibility standards / spec as per above
- [x] If relevant, break down component into `Styles Only` and `React` component structures
- [x] Ensure all variants of components are documented as appropriate 
- [x] Ensure unit test coverage is adequate for component
- [x] Update documentation in MDX file as per guidelines
- [ ] Changelog updated to reflect a single beta version per component ideally

**Release Checklist**

- [ ] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**note:** One of the (currently undocumented) behaviours the DS expects of a text area is the ability for it to resize itself between some defined minimum and maximum number of rows. #134 is seeking clarification on whether we are willing to conditionally leverage an experimental CSS property, `field-sizing`, to enable this resizing behaviour to be present for CSS-only consumers on specific browsers.

**Comment by willmcvay** [comment]
@kurtdoherty I am totally fine on using modern CSS features - we have auto-prefixer in the build to handle browser quirks - the only issue will be our friend Safari - we have a lot of mobile iOS users so as long as there is a graceful fallback, it's all good.

**Comment by kurtdoherty** [comment]
Andrei as signed off on this via [Slack](https://consoleau.slack.com/archives/CFH8NGFLN/p1723529619315269).

I'm not sure what else needs to occur before marking this work as done. He did flag that the TextArea component should handle the label and form validation message concerns, but understands we need to have a larger conversation about how we technically facilitate that via Elements.
