### ISSUE TITLE
v5 component refactor: Avatar 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/elements#137]
**Abstract**

_As part of the v5 Elements release, each component will be reviewed and refactored to ensure best practice and design system alignment_

**Specification**

- Is new component or existing? Existing - called 'Avatar' in Elements. However, should be reviewed/adhere to variants in the DS e.g. circle, rectangle & square 
- Is the component being re-named? No but should review variants and ensure they are aligned
- Is the component design signed off by product and design? Yes
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to DS in Figma](https://www.figma.com/design/6CaivqdlTX0UkFYJkpBKDu/Reapit-DS?node-id=428-7281&t=8GcgX59FmafMRAda-4)
- [Link to Design Guidelines](https://www.figma.com/design/pJ96bxoEFStjjIbAPy0Jaj/Design-Guidelines?node-id=945-25698&t=T27RmqyqogSxbWuo-4)
- [Link to Elements](https://elements.reapit.cloud/?path=/docs/avatar--docs)
- [Accessibility requirements](https://www.w3.org/WAI/tutorials/images/informative/)

**Developer Checklist**

- [x] Styles alignment between Design System and Elements
- [x] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [x] Align with accessibility standards / spec as per above
- [x] If relevant, break down component into `Styles Only` and `React` component structures
- [x] Ensure all variants of components are documented as appropriate 
- [x] Ensure unit test coverage is adequate for component
- [x] Update documentation in MDX file as per guidelines
- [ ] Changelog updated to reflect a single beta version per component ideally

**Release Checklist**

- [x] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**Comment by ksolanki7** [comment]
After discussing with the Design team, I am moving this ticket back to the "To Do" column, as there are still clarifications needed and updates required for the component. The ticket will not be ready for development until these items are resolved by the Design team. Please refrain from picking up this ticket until it has been cleared by the Design team.

**Comment by ksolanki7** [comment]
@nurm717123 This ticket is ready to be picked. Here is the dev ready figma link - [Figma Link](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=1288-7422&node-type=canvas&m=dev)

**Comment by nurm717123** [comment]
### Context: 
- there is three variants of avatar which one of them have different style than other that require more discussion (e.g `rectangle` avatar could accept image and have completely different style than `circle` and `square` avatar)
- Three of them will require too much code for a single PR.
- Avatar `circle` and `square` looks like have same style, the only different is its shape

### Proposal
given the context above I propose to make 2 components out of it to complete this ticket:
1. Avatar (shape=circle/square, variants=letter/icon,  src=string/IconName, size=small/medium, style=default/purple)
2. AvatarRectangle  (variants=residential/commercial,  fill=image/placeholder, size=small/medium, src=string/undefined)

and to complete 2 of them, I've planned to have 3 pr:
1. Avatar (circle/square)
2. AvatarRectangle (residential)
3. AvatarRectangle (commersial)

### code snippets
```javascript
// avatar
<span role="presentation" {... props}> // role can be overriden later
  src (as <Icon/> or string)
</span>
```
```javascript
// avatar-rectangle
<span role="presentation" classname="el-avatar-rectangle-container" {... props}> // role can be overriden later 
(image or placeholder image) as <img classname="el-avatar-rectangle-residential" />
//or
(image or placeholder image) as <img classname="el-avatar-rectangle-commercial" />
<img classname="el-avatar-rectangle-commercial-layer" />
</span>
```

Should there be any incorrect component or prop names or any other, I would be happy to discuss it.

cc: @kurtdoherty @adrian-reapit

**Comment by kurtdoherty** [comment]
@nurm717123 I don't think AvatarRectangle is required at this stage (I've asked for confirmation from Andrei in the Figma file though). 

**question:** I don't understand why you're opting to handle the icon via a `src` prop. Can you please explain your thinking here?

**issue:** I don't think we should use a prop called `style` for the default/purple option. I think we should treat that as a reserved prop given it's normally how inline styles would be supplied. We need to come up with a different name here; perhaps Design have some ideas. I've started a thread on the Figma file about this.

**suggestion:** I don't think we need an explicit `variant: 'letters' | 'icon'` prop. Seems more appropriate for us to handle that via `children` so that consumers do:

```html
<Avatar shape="square">KD</Avatar>
<Avatar shape="circle">
  <MyIcon />
</Avatar>
```

**Comment by nurm717123** [comment]
> @nurm717123 I don't think AvatarRectangle is required at this stage (I've asked for confirmation from Andrei in the Figma file though).

yes, I've seen your comment there, just updated the proposal couple hours ago but I think having 3 of them would be nice (in case `table` component would need this) so I revert it back cc @ksolanki7 

> question: I don't understand why you're opting to handle the icon via a src prop. Can you please explain your thinking here?

sure, i think its easier so that the consumer just need to use the `variant` prop to control what they want

> issue: I don't think we should use a prop called style for the default/purple option

yes, I think the better name would be `intent` but I just follow what in the spec for initial

> suggestion: I don't think we need an explicit variant: 'letters' | 'icon' prop. Seems more appropriate for us to handle that via children 

ok, I got your point, I think better use this approach to make it the same pattern for new component 👍

**Comment by nurm717123** [comment]
and also there is another component e.g old `Table` component that use the old `avatar`, I think I will rename the previous avatar to `DeperecatedAvatar` , because the square and circle avatar didn't support image, yet.

**Comment by kurtdoherty** [comment]
**suggestion:** Deprecating sounds reasonable, but it could be good for you to communicate here what differences exist between the prop interfaces of the old and new avatar components. It may be simple to have some deprecated props on the new avatar that support what the existing one needs.

**note:** If you do take the deprecation route, please do all that work in a separate PR to the implementation of the new avatar component/s.

**Comment by nurm717123** [comment]
> suggestion: Deprecating sounds reasonable, but it could be good for you to communicate here what differences exist between the prop interfaces of the old and new avatar components. It may be simple to have some deprecated props on the new avatar that support what the existing one needs.

yes, basically the old avatar consumer is `Nav (old)`, `Card`, `Table (old)`, and PageHeader`, and the main difference is:
1. it use `type` (profile/image) in new versoin it would might be `shape` (circle/square) 
2. it could use the `children` or it could use `src` props  instead
3. has style different, .eg old avatar type=image (square) doesn't have border radius

> note: If you do take the deprecation route, please do all that work in a separate PR to the implementation of the new avatar component/s.

yes sure 👍 , I think I more leaning to it but I still need others thought about it whether we want to force the older consumer to use newest design or not 🤔

**Comment by nurm717123** [comment]
Great 👍, then based on the last comment I am planning to create 3 pr for this:
1. deprecate previous avatar
2. Avatar (circle/square)
3. AvatarRectangle

**Comment by kurtdoherty** [comment]
Yep, looks good @nurm717123 👍 

**suggestion:** When it comes to `AvatarRectangle`, it would be worth trying out the [\<object\> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object). It supports behaviour like:

```html
<object
  data="path/to/main/image.png"
  type="image/png"
  width="600"
  height="140">
  <img src="path/to/fallback/image.jpg" />
</object>
```

Where the `<img>` is used only as a fallback if the object element's data fails to load. It may even be possible for us to use an `<svg>` element or [data URL](https://developer.mozilla.org/en-US/docs/Web/URI/Schemes/data).

**Comment by nurm717123** [comment]
Absolutely, I’d like to give that a try first. Thank you

**Comment by nurm717123** [comment]
Hi @kurtdoherty, I've tried the `object` tag, and the result is only the `Residential` variant is supported, because the `Commercial` one has bottom placeholder.

### image version
![Image](https://github.com/user-attachments/assets/8dd016fb-7717-4a5f-bc55-97418669fd63)

### placeholder version
![Image](https://github.com/user-attachments/assets/90e74c2c-6be5-476b-abeb-fe29647df04a)

so I think I can implement the `object` only for the `Residential` and use normal `img` approach for `Commercial`

**Comment by nurm717123** [comment]
Hi @kurtdoherty after I tried the `object`, I found some issue to implement it to `AvatarRectangle` which is:

1. it requires to specify `type` (e.g type="image/jpeg") to display the image (especially jpeg) correctly
2. it doesn't support image-fit props like <img/> (fill/contain/cover .etc in case consumer want to custom it)

https://codesandbox.io/p/sandbox/3w9jt5

I think `img` tag is enough for `AvatarRectangle` and easy to use.

**Comment by kurtdoherty** [comment]
**question:** You seem to suggest that specifying the mime type is not acceptable? If so, why?

**note:** I believe you mean [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit), and it seems to work fine...

**Comment by nurm717123** [comment]
> Here's an updated sandbox: https://codesandbox.io/p/sandbox/3w9jt5

the sandbox seems not updated 👀 

> question: You seem to suggest that specifying the mime type is not acceptable? If so, why?

yes, I think that it require us to specify the valid image type (e.g only jpg image is allowed to use this component)

> By not specifying the mime type, I believe the browser defaults to displaying the object via an iframe, which is why you see scrollbars and need to target a child <html> element.

I have tried it in the sandbox by adding overflow hidden to the html of the object but still doesn't work (it work if I did it in devtool though 🤔 ).

**Comment by nurm717123** [comment]
> I have tried it in the sandbox by adding overflow hidden to the html of the object but still doesn't work (it work if I did it in devtool though 🤔 ).

turns out it a browser specific issue, I'm using Brave browser by default it doesn't work, but in Firefox it works

**Comment by kurtdoherty** [comment]
🤦 Sorry! I didn't use the right link... here's the updated one: https://codesandbox.io/p/sandbox/tender-chaplygin-gkclqq

> question: You seem to suggest that specifying the mime type is not acceptable? If so, why?
> yes, I think that it require us to specify the valid image type (e.g only jpg image is allowed to use this component)

We can use any valid mime type, so long as it matches to the kind of resource we're referencing in the `data` attribute. I would expect the mime type to be known by consumers, so it feels fine to require them to explicitly provide it 🤷‍♂️ 

That said, we don't _have_ to use `<object>`. I just liked the built-in fallback behaviour it provided. It looks like we may lose some performance related options that maybe aren't things we want to lose, like the [loading](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading) attribute that `<img>` has... I can't find any good docs on how `<object>` behaves in this regard, so I don't know if it <object> elements are always lazily loaded, or always eagerly loaded.

**Comment by nurm717123** [comment]
ok, I will use `onError` for that, and for html user I think a classname that is actually box colored grey (just like the design spec) would do (e.g `commercial-placeholder` something like that)👍
