### ISSUE TITLE
v5 new components: Menu (basic) and MenuButton

### ISSUE THREAD

**Issue by adrian-reapit** [reapit/elements#163]
**Abstract**

To support the AppBar improvements an initial version of the Menu component should be made which can be used in a MenuButton and extended later with all other Menu features. 

Menu should provide the basic design with optional title and list of items

![Image](https://github.com/user-attachments/assets/a948bc7b-91b4-43d4-a46a-0d8a99f7a493)

MenuButton toggles the view of Menu below. 

- Menu alignment can be set to left, middle or right side of the button. 
- The Y offset of the Menu can be changed
- The chevron can flip to match the menu visibility
- Button props such as intent and icon can be used in MenuButton 

![Image](https://github.com/user-attachments/assets/3b7f6925-4a7a-4dbb-b8b9-0391730907b8)

**Specification**

- Is new component or existing? New
- Is the component design signed off by product and design?  Menu is signed off. MenuButton is signed off as part of the Navigation changes but not as a standalone component
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to DS in Figma](https://www.figma.com/design/6CaivqdlTX0UkFYJkpBKDu/Reapit-DS?node-id=428-8537&node-type=FRAME&t=vLPA7faa1KEJRIii-0)
- [Link to AppBar design in Figma](https://github.com/orgs/reapit/projects/16/views/1?pane=issue&itemId=78443969) 

 
**Developer Checklist**

- [x] Styles alignment between Design System and Elements
- [x] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [x] Align with accessibility standards / spec as per above
- [x] If relevant, break down component into Styles Only and React component structures
- [x] Ensure all variants of components are documented as appropriate
- [x] Ensure unit test coverage is adequate for component
- [x] Update documentation in MDX file as per guidelines
- [ ] Changelog updated to reflect a single beta version per component ideally

**Release Checklist**

- [ ] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**Comment by kurtdoherty** [comment]
**suggestion:** The newly baselined [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) could really help simplify the implementation of a Menu component. It may be a touch early to rely on though, it's pretty fresh (it achieved baseline in April 2024)...

> MenuButton is signed off as part of the Navigation changes but not as a standalone component

**question:** What's the plan here then. If it's not signed off as a dedicated component, should we be adding it to Elements? 
**suggestion:** Perhaps we should provide a `useMenu` hook instead that can be used to wire up any button/link with a Menu?

**Comment by nurm717123** [comment]
Hi @adrian-reapit  and @kurtdoherty , for what I understood from my first pr, here is my plan on how I can complete the ticket.

### Context: 
- there are significant lines of codes required in one PR to build the complete menu
- there is more discussion needed for whether the menu (in this ticket) going to cover all variants of the menu

### Proposal
given the context above I propose that the scope of this ticket will be the creation of the menu (only basic version) and menu-button (that will present inside app-bar), which going to be broken down in several pr:

1. Menu (#171) : the base menu compound component, including the sub component (the trigger, and the popover) which using the react-context to manage the open state in between
2. Menu item group and Menu item (button, link)
3. Menu item (radio, or checkbox)
4. Keyboard interaction (a11y)
5. Menu button

additional requirements
- the y offset will be automatically adjusted (will be covered in 5th pr)
- the x offset can be configured manually using (`aligntment`, or `position` props)
- the menu can be closed by clicking the outside of the menu (without disabling any `:hover` style for any element behind menu) , button inside menu, or the trigger

non requirements
- cover style adjustment for consumer who using non native html (button, link, .etc) for Menu item
- busy state of Menu item

### code snippets
```javascript
// menu
<Menu>
  <Menu.Trigger>
    {({ getTriggerProps, isOpen }) => (
      // menu-button (e.g app-bar's menu-button)
      <AppBarMenuButtonToggler {...getTriggerProps()} isExpanded={isOpen} label="Some label" />
    )}
  </Menu.Trigger>
  <Menu.Popover>
    <Menu.List>
      <Menu.Group title="some title">
        <Menu.Item>{/* some link or button */}</Menu.Item>
        <Menu.Item>{/* some link or button */}</Menu.Item>
        <Menu.Item>{/* some link or button */}</Menu.Item>
      </Menu.Group>
    </Menu.List>
  </Menu.Popover>
</Menu>
```

**Comment by kurtdoherty** [comment]
@nurm717123 This is great! Thanks for outlining the PR progression and describing the requirements you're aware of and things we know we won't be considering. A few comments:

- PRs 2 and 3 involve very closely related concerns. Radio and Checkbox items (and the groups they may be in) are pretty tightly related to the basic menu item and menu group components. To help us avoid decisions in PR 2 that create unintended consequences in PR 3, I think it would be good to go into a little more detail about how we'll facilitate radio and checkbox items now, rather than later. That way we can lay good foundations in PR 2. Does that make sense?
- I think it's worth us getting some direction (from @HollyJoyPhillips perhaps) on the importance of PR 4 (keyboard interaction). Personally, I think a11y is really important and we should spend time getting it right, but I also know we have a lot of components to deliver in a pretty short period of time, so perhaps its something that we can come back to once we've got more of the v5 migration work done? 🤔 
- I'm curious to know how you aim to have the y-offset automatically adjusted. Do I have to wait until PR 5 to find out? 😛😅

**Comment by nurm717123** [comment]
thanks Kurt, that's make sense.
> PRs 2 and 3 involve very closely related concerns. Radio and Checkbox items (and the groups they may be in) are pretty tightly
 
yes, so for the PR's 2 and 3 my initial approach will be,

2nd pr is about a MenuGroup and Item, I'm planning to use 'ul` for the Menu group and `li` for Menu item, the reason is just simply it can be used to make list of all of the variants (button, radio, or checkbox, .etc).

reference:
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox/
https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio-activedescendant/
https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/

and then expose them from atoms so it can be used like this

```javascript
<Menu.List>
    <Menu.Group title="some title">
        <Menu.Item>{/* a link or button */}</Menu.Item>
        <Menu.Item>{/* a link or button */}</Menu.Item>
        <Menu.Item>{/* a link or button */}</Menu.Item>
    </Menu.Group>
    <Menu.Group title="checkbox and radio version">
        <Menu.OptionItem onChange={onChangeHandler} defaultChecked label="some label"  /> {/* assuming the label is unique it could be used as a value too */}
    </Menu.Group>
</Menu.List>
```
> I think it's worth us getting some direction (from @HollyJoyPhillips perhaps) on the importance of PR 4 (keyboard interaction)

agree

> I'm curious to know how you aim to have the y-offset automatically adjusted. Do I have to wait until PR 5 to find out? 😛😅

my plan is to put a `useLayoutEffect` inside the `Menu.Popover`, and it will use the same approach like the `useClickOutside` listener hook which is to use the parent of popover and calculate available space around the trigger button

```javascript
// need to try to add a base class name for trigger
const triggerBtn = parentElement.current.querySelector(`.${getTriggerProps().className}`)
const popover = popoverRef
```
should I have to include it on the next pr though 🤔

**Comment by kurtdoherty** [comment]
@nurm717123 I have no problems with you descoping the radio and checkbox style menu items to a separate ticket 👍 I definitely think the implementation of those kinds of items needs some careful thought. From what you've shown above, I'll have some clarifying questions when you create a ticket for them.

> my plan is to put a useLayoutEffect inside the Menu.Popover, and it will use the same approach like the useClickOutside listener hook which is to use the parent of popover and calculate available space around the trigger button

I'm not sure I understand how the layout effect will know what offset should be used, but we can tackle that when you get to that stage of the work 👍

**Comment by nurm717123** [comment]
> I have no problems with you descoping the radio and checkbox style menu items to a separate ticket 👍 I definitely think the implementation of those kinds of items needs some careful thought. From what you've shown above, I'll have some clarifying questions when you create a ticket for them.

ok, thank you

> For PR 2, which will be focused on the basic group and item, I think what you've shown above looks good. I'm just a little uncertain still on whether native or elements within each item will be sufficient; e.g. what about <div role="button" onClick={...}>My fake, but accessible button</div>? That would, I believe, represent a valid button, but I don't think that would work with how you are likely aiming to style the menu items, or handle the closing of the menu when an item is clicked 🤔

I think adding the style only to the first div would work, and adding more condition to also close when the `div[role='button']` will work too, but let me try 👍 

> I'm not sure I understand how the layout effect will know what offset should be used, but we can tackle that when you get to that stage of the work 👍

👍

**Comment by HollyJoyPhillips** [comment]
I've spoken to Will and in interest of keeping the PR's a sensible size, and that we are still in beta, we keep the patterns suggested on the W3 and write up a separate spec of implementation for additional standards. 

https://www.w3.org/WAI/ARIA/apg/patterns/menubar/
https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/

**Comment by kurtdoherty** [comment]
@HollyJoyPhillips Just to clarify, it is those specs that include the _keyboard interaction_ Nur has proposed to implement in the 4th PR for this work. There are no "additional standards" being suggested.

**Comment by nurm717123** [comment]
I think I can do the main keyboard interaction, while if there is more complex spec is missing then I can do in different ticket, 
here is the pr https://github.com/reapit/elements/pull/190

**Comment by nurm717123** [comment]
turns out there is another component in figma called `MenuButton` too, which one we should rename

**Comment by nurm717123** [comment]
![image](https://github.com/user-attachments/assets/cf4ef61c-0a50-453f-9263-e6c58c259785)

after I go through the figma again the component there is named `NavDropdownButton`, I have updated the pr
