### ISSUE TITLE
v5 new components: NavIconItem

### ISSUE THREAD

**Issue by adrian-reapit** [reapit/elements#164]
**Abstract**

To support the **AppBar** improvements the **NavIconButton** and **NavIconMenuButton** components should be made which can be used in secondary and footer navigation

![Image](https://github.com/user-attachments/assets/7f4433cf-7de3-432a-80cb-114c2ba401b2)

![Image](https://github.com/user-attachments/assets/231f0d86-4369-4f95-b638-fb1302c6efd0)

![Image](https://github.com/user-attachments/assets/858ff5d1-fc1f-4008-a632-580b3dc1cc78)

**NavIconButton** is a button with a centred icon and optional centred text below. It can be a private component used by **AppBar**

- icon and text highlight can be controlled 
- a notification badge can be shown
- the badge is an icon and so we could allow other icons and intent to be shown 

**NavIconMenuButton** is an extended version of **NavIconButton** which shows the menu above or below

**Specification**

- Is new component or existing? New
- Is the component design signed off by product and design?  Signed off as part of the AppBar changes
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to AppBar design in Figma](https://github.com/orgs/reapit/projects/16/views/1?pane=issue&itemId=78443969) 

 
**Developer Checklist**

- [ ] Styles alignment between Design System and Elements
- [ ] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [ ] Align with accessibility standards / spec as per above
- [ ] If relevant, break down component into Styles Only and React component structures
- [ ] Ensure all variants of components are documented as appropriate
- [ ] Ensure unit test coverage is adequate for component
- [ ] Update documentation in MDX file as per guidelines
- [ ] Changelog updated to reflect a single beta version per component ideally

**Release Checklist**

- [ ] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**Comment by kurtdoherty** [comment]
**issue:** @azkanurf-ss I think you may be confusing two different components and treating them as one. The "Nav Icon Item" is exclusively used for the Secondary Nav and only has a visible label when hovered or focused (i.e. the when the tooltip is displayed), while the screenshot you show of an icon + visible label is the "Bottom Bar Item" and is used exclusively for the Bottom Bar.

**issue:** As I've recommended for the Button work currently in-progress, we should avoid tightly coupling our components to the current `Icon` component. Instead, we should simply accept a generic ReactNode for the icon. I would probably take the same approach with the badge as well.

**suggestion:** I know the App bar design specs only show the dot-style badge, but the Design System as a numerical style badge as well. I would be worth clarifying with Design whether secondary nav items should support the numerical style.

**issue:** Nav items will need to support rendering out as both `<a>` elements and `<button>` elements. I don't see any comments above regarding how you'll handle that.

**question**: Tooltips and badges are both atoms in their own rights. Are you planning on implementing those components as part of this work?

**Comment by azkanurf-ss** [comment]
Hi @kurtdoherty, the Design team has responded to the query [here](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=1212-9812#1002385758). Do you think we still need to use the Icon approach for the Badge?

**Comment by kurtdoherty** [comment]
> I was considering creating a base component for NavIconItem and BottomBarItem

I think we need to be careful creating dependencies between components that the Design team have kept separate. I don't think the cost of duplicating some styles etc will be too high for either of these components, so I'm personally okay to keep them completely separate. If you feel differently, it's worth raising with the Design team (if you haven't already).

> the Design team has responded to the query [here](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=1212-9812#1002385758). Do you think we still need to use the Icon approach for the Badge?

Yes, I think that response confirms we probably want the flexibility to provide different badges in future, so I think accepting a `ReactNode` prop for the badge is fine. Do we have a finalised design spec for the Badge component? If not, I think that's even more reason to just accept a `ReactNode` here.

> I'm still uncertain about the names for <NavIconItem /> and <NavItemContainer />.

I'm not sure I understand the need for the `NavItemContainer`... what do you envision it facilitating? Same with the `IconContainer` component you show in the snippets above.

**Comment by kurtdoherty** [comment]
**question:** is the use of `title` for the `tooltip` a temporary decision? I ask because the native `title` attribute does not produce a tooltip that we can style with CSS (at least to my knowledge), so I'm not sure how using that attribute allows us to produce the tooltip shown in the designs...

**Comment by kurtdoherty** [comment]
**issue:** re `icon`, I don't think we should be doing `{isValidElement(icon) ? <>{icon}</> : <Icon icon={icon} />}`. That still implicitly couples us to the existing `Icon` component, which is what we're trying to avoid by accepting any `ReactNode` in the first place.

**Comment by azkanurf-ss** [comment]
> I think we need to be careful creating dependencies between components that the Design team have kept separate. I don't think the cost of duplicating some styles etc will be too high for either of these components, so I'm personally okay to keep them completely separate.

I understand your point about keeping components separate to avoid unnecessary dependencies. I think it is also easier to maintain if there's a major update in the future for that component. So, I’m on board with keeping them distinct.

> I'm not sure I understand the need for the NavItemContainer... what do you envision it facilitating? Same with the IconContainer component you show in the snippets above.

Sorry, we can ignore this since we plan to separate both components.

**Comment by kurtdoherty** [comment]
> The design team has already provided the handoff file for the badge [here](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=1245-7191&m=dev), but I think we need a smaller badge size for the Nav Icon Item.

I think that's a completely different component 🤔 I think I've gotten confused about the component's name and I can't seem to find the component I thought did exist for this dot and a numerical version of it... I think we need to ask Design for some clarity.

**Comment by kurtdoherty** [comment]
@ss-dimasm no worries. I agree that work can start 👍 

I think we just need to work with Design to find out what component the "dot" actually represents (if any) so that we can name the associated prop correctly. Since `Badge` seems to be something completely different, I'm not sure that's an appropriate name for a prop on this `NavIconItem`.

**Comment by ss-dimasm** [comment]
Following the discussion from #191 . we're still need to polish this component by adding the red dot indicator and also a tooltip; but before moving forward; I've raise a question to Design Team via Figma; we could track it in [here](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=16-4746&m=dev#1016315051)

**Comment by ss-dimasm** [comment]
> but before moving forward; I've raise a question to Design Team via Figma; we could track it in [here](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=16-4746&m=dev#1016315051)

it depends on the answer, if they treat the Red Dot Indicator and Tooltip as a shared component, I think it's better to raise a new ticket for this; and continue to work the `NavIconItem` after it's merged; but if not, looks like we could moving straight forward to implement directly to the `NavIconItem`

**Comment by ss-dimasm** [comment]
Hi @kurtdoherty, based on what Andrei said, it seems we could continue to implement the `ToolTip` and "`Red Dot`" as part of the `NavIconItem`. What do you think about that?

**Comment by ss-dimasm** [comment]
I raised a comment to track the ticket's state, considering the current situation and our dependence on some answers from the Design Team

- [ ] Initiate the scaffold of `NavIconItem` following the design
- [ ] Integrate with ToolTip component (awaiting the Design Team's answer [query link](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=16-4746&m=dev#1016315051))
- [ ] Integrate with red dot indicator (awaiting the Design Team's answer [query link](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=16-4746&m=dev#1016315051))

**Comment by kurtdoherty** [comment]
> Hi @kurtdoherty, based on what Andrei said, it seems we could continue to implement the `ToolTip` and "`Red Dot`" as part of the `NavIconItem`. What do you think about that? and he highlight that it's a dedicated component for "App Bar"
> 
> reference https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=16-4746&m=dev#1016315051

I think further conversation is still required, particularly around the tooltip.

**Comment by ss-dimasm** [comment]
> I think further conversation is still required, particularly around the tooltip

in the meantime, can we add the red dot indicator directly to this component? we'll also need to add it to #192

**Comment by kurtdoherty** [comment]
Yep, I think so 👍

**Comment by andrei-dragut** [comment]
@ss-dimasm Looks good. You can close the ticket
