### ISSUE TITLE
v5 new components: BottomBarItem

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/elements#192]
**Abstract**

To support the AppBar improvements, the `BottomBarItem` component should be made which can be used as part of `BottomBar` component

BottomBarItem design specification on Figma

![{670233AA-9863-411C-86DF-FE4311380F77}](https://github.com/user-attachments/assets/d6a96f27-230f-4b6b-bac6-8244e9eb1dba)

**Specification**

- Is new component or existing? New
- Is the component design signed off by product and design?  Signed off as part of the AppBar changes
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to DS in Figma](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=16-4738&node-type=symbol&m=dev)

**Developer Checklist**

- [x] Styles alignment between Design System and Elements
- [x] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [x] Align with accessibility standards / spec as per above
- [x] If relevant, break down component into `Styles Only` and `React` component structures
- [x] Ensure all variants of components are documented as appropriate 
- [x] Ensure unit test coverage is adequate for component
- [x] Update documentation in MDX file as per guidelines
- [ ] Changelog updated to reflect a single beta version per component ideally

**Release Checklist**

- [x] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**Comment by ss-dimasm** [comment]
Hello @kurtdoherty and @adrian-reapit ,I 'm creating this ticket to focus on the [BottomBarIcon](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=16-4737&node-type=frame&m=dev) component, based on the design. This component is distinct from the one in #164 and has its own complexities, so it's best to treat it as a separate component.

**Comment by ss-dimasm** [comment]
I raised a comment to track the ticket's state, considering the current situation and our dependence on some answers from the Design Team

[ ] Initiate the scaffold of `BottomBarItem` following the design
[ ] Integrate with red dot indicator (awaiting the Design Team's answer [query link](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF?node-id=16-4746&m=dev#1016315051))

**Comment by andrei-dragut** [comment]
@ss-dimasm All good. You can close the ticket
