### ISSUE TITLE
v5 new component: AvatarButton (App-bar)

### ISSUE THREAD

**Issue by nurm717123** [reapit/elements#203]
**Abstract**

_As part of the v5 Elements release, the ticket #153 was created. To break it into smaller part and allow for more focused discussions, this ticket has been created._

***app bar (parent)***
![image](https://github.com/user-attachments/assets/dbc50742-49e5-4c0d-aebf-2305aa72bfc8)

***this ticket***
![image](https://github.com/user-attachments/assets/c015db6b-62c2-4e41-b5e6-adddc6767af1)

the component should extends the new Avatar component https://github.com/reapit/elements/issues/137

**Specification**

- Is new component or existing? new
- Is the component being re-named? no
- Is the component design signed off by product and design? yes, as part of the new app bar
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to DS in Figma](https://www.figma.com/design/6CaivqdlTX0UkFYJkpBKDu/Reapit-DS?node-id=52-879&node-type=symbol&m=dev)
- [Link to Elements Audit in Figma](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=16-4808&node-type=instance&m=dev)
- [Accessibility requirements](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/)
- [Parent ticket](https://github.com/reapit/elements/issues/153)

**Developer Checklist**

- [ ] Styles alignment between Design System and Elements
- [ ] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [ ] Align with accessibility standards / spec as per above
- [ ] If relevant, break down component into `Styles Only` and `React` component structures
- [ ] Ensure all variants of components are documented as appropriate 
- [ ] Ensure unit test coverage is adequate for component
- [ ] Update documentation in MDX file as per guidelines

**Release Checklist**

- [ ] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**Comment by kurtdoherty** [comment]
@nurm717123 can you please outline the proposed interface for this component _before_ you submit any work for review? 🙏 The whole point behind a "design doc" (even a simple "here's the component's prop interface") is to get agreement before we invest in writing code.

**Comment by nurm717123** [comment]
> @nurm717123 can you please outline the proposed interface for this component before you submit any work for review?
thanks Kurt for reminding me, ok I will make that. and by the way this component will extends the new Avatar component, so it will depends to this ticket #137

**Comment by kurtdoherty** [comment]
Thanks @nurm717123. I'm more interested in the React component's prop interface, not its implementation detail. How do you see the React component being used?

**Comment by nurm717123** [comment]
Ah yes, I forgot to include that. I think it would be something like this:

```javascript
// since it should always use avatar with `letter` variant
// this way consumer can still set whatever label they want
<AvatarButton label="NM" onClick={onClickHandler} />
```

**Comment by kurtdoherty** [comment]
Thanks. I'm not sure we need to lock it down to the letter variant; feels premature to me, but I also won't lose sleep over it. Lastly, because this component is intended to be used with other components (the Menu), its valuable to explicitly show how that integration is achieved. As a reader, I currently have to make assumptions about how you plan to have a menu appear when the avatar button is clicked, but what I assume may not be what you are planning.

**Comment by nurm717123** [comment]
Sure, I'm sure it will be something like this:
```javascript
<Menu>
  <Menu.Trigger>
    {({getPopoverProps}) => <AvatarButton {... getPopoverProps({onClick: additionalHandlerIfNeeded})} label="NM"  />}
  </Menu.Trigger>
  <Menu.Popover>
    ... // Menu.List, Items, .etc 
  </Menu.Popover>
</Menu>
