### ISSUE TITLE
v5 Button Component Refactor - Housekeeping updates

### ISSUE THREAD

**Issue by ksolanki7** [reapit/elements#226]
**Background context:**

Several housekeeping updates are needed to enhance the storybook representation of the Button component. Below is the background context for these updates.

- The onClick handler for anchor-type buttons appears non-functional and does not trigger as expected.
- The onClick handler does not correctly handle interactions for a disabled button.
- The icon container CSS has conflicts with overrides for different variants, likely due to a placement issue in the styles file.
- The Button component in the playbook lacks robust support for controls, making it challenging to test the component with various properties and accurately validate the UI.

**Specification or tasks to perform:**

- [x] Resolve the issue with the anchor-type button to ensure the onClick handler functions as expected.
- [x] Update onClick handler for disabled button to avoid calling user's onClick event.
- [x] Address the CSS conflicts in the icon container to correctly handle overrides for different variants.
- [x] Enhance Storybook by improving controls for each Button story, where applicable.

[Link to Component](https://elements-beta.dev.paas.reapit.cloud/?path=/docs/components-button--docs)

**Comment by kurtdoherty** [comment]
> The Button component in the playbook...

**question:** What is the "playbook"? Do you mean the Button's stories?

**Comment by ksolanki7** [comment]
@kurtdoherty I have updated the issue description.

**Comment by kurtdoherty** [comment]
> The Button component in the playbook lacks robust support for controls, making it challenging to test the component with various properties and accurately validate the UI.

**note:** FWIW, this is what unit tests are for, not storybook (though maybe in future we'll have the two aligned) 😃

**Comment by ksolanki7** [comment]
@kurtdoherty Sure, this is more for the Design team to test the component with different props for UI testing. My approach at the moment is not add support to all stories but at least to default, so that Design team can play with the component.
