### ISSUE TITLE
Messages and tasks API doesn't support filtering completed status

### ISSUE THREAD

**Issue by hoangnguyentci** [reapit/elements#231]
**Is your feature request related to a problem? Please describe.**
In Agency Cloud, we can filter messages and tasks by completed status

**Describe the solution you'd like**
API URL: https://platform.reapit.cloud/tasks/
Messages and tasks API doesn't support filtering completed status

**Describe alternatives you've considered**
We would like to have completed status filter in Messages and tasks API similar to Agency Cloud

**Additional context**
In Agency Cloud screenshot:

**Comment by kurtdoherty** [comment]
Hi @hoangnguyentci, I think you may have the wrong repo... `@reapit/elements` has no involvement in the UI you're describing above. I may be wrong, but I wonder if this is more about the Reapit Foundations API?

**Comment by hoangnguyentci** [comment]
Hi @kurtdoherty, yes, this is about Reapit Foundations API. But I can't create issue in Reapit Foundations repo
![Screenshot 2024-12-03 at 12 39 40](https://github.com/user-attachments/assets/58db89ed-9a97-4872-8cd0-4d4538b098fa)
![Screenshot 2024-12-03 at 12 39 12](https://github.com/user-attachments/assets/1c6f2e33-de13-476a-9fb7-61e67be99110)

**Comment by kurtdoherty** [comment]
@willmcvay can you please advise on where/how @hoangnguyentci can raise a feature request for Foundations API?

**Comment by hoangnguyentci** [comment]
@willmcvay @kurtdoherty how can I raise a feature request for Foundations API?

**Comment by willmcvay** [comment]
> @willmcvay @kurtdoherty how can I raise a feature request for Foundations API?

@hoangnguyentci  Please follow the steps in the documentation here https://foundations-documentation.reapit.cloud/dev-requests - these are the same docs hosted in the developer portal for future reference.

I have also deleted the image from the ticket since it contains PID. Please be mindful of posting screenshots in public issues.
