### ISSUE TITLE
Drop React peer dependency from 18.x to 17.x

### ISSUE THREAD

**Issue by kurtdoherty** [reapit/elements#59]
**Is your feature request related to a problem? Please describe.**
The Console Cloud product is currently running on React 17. An upgrade to React 18 depends on a large enough amount of work that it will delay our ability to leverage Elements on the short- and medium-term if it maintains a peer dependency on React 18.

**Describe the solution you'd like**
If we can drop the React peer dependency from 18.x to 17.x, that will enable the Console Cloud product to leverage Elements sooner.

**Describe alternatives you've considered**
We could delay adoption of Elements in Console Cloud and continue to invest in our own Design System component library, but this represents a considerable duplication of effort, as we'll be trying to implement Design System components in React just like Elements will be. It also means that a good portion of Reapit's experienced React engineers will not be actively using or contributing to Elements, which may impact its adoption and growth.

**Comment by willmcvay** [comment]
@kurtdoherty Sorry for the slow reply on this one!

So I'm not against reducing the peer dependency _per se_, preferring to be pragmatic however, we'd need to discuss the cost-benefit analysis - maybe off line. Things we'd need to consider;

- Some remediation would need to be done on the Elements repo to polyfill any React 18 hooks we are using like useId - not a big deal, but worthy of comment
- Testing - we don't have any React 17 in the estate and all our internal libs are largely kept up to date. Secondary dependencies like React Query, Router and Hook Form are all 18 dependent so it's non-trivial. You would need to validate each release was non-breaking for 17 in this case, which would be an overhead for your team. 
- React 19 - seems to be coming soon and we'll need to update to support when it does. In this case, it seems a stretch to support 3 major versions. Might be possible, just not sure.

I guess my main question would be, have you got an estimate on how much would be involved to do the 17-18 migration your end and whether it would be worth prioritising this vs, the ongoing overhead of maintaining 17 support in Elements? Without that, it's hard to make an informed decision on the best course of action.

**Comment by kurtdoherty** [comment]
I believe the main blocker for us is our extensive use of MUI v4 components. These still make up the bulk of our React-based UI for Console Cloud. If we can't migrate the MUI v4 UI, and our AngularJS UI, to Elements, we'll be rewriting our front end twice:

1. Replacing AngularJS and MUI v4 with our react-ui-core component library (which is MUI v5 based); then
2. Replacing react-ui-core with Elements.

In addition to the cost of those two migrations, we'd also be investing in react-ui-core to keep it up-to-date with the Design System which would obviously duplicate much of the effort invested into Elements itself.

Overall, I think it would be considerably cheaper long-term for the business if we can enable Console Cloud to leverage Elements now instead of later. Happy to dig into this more with you via a different channel if you'd prefer.

**Comment by kurtdoherty** [comment]
One potential option that comes to mind is if Elements is compatible with tree-shaking/provides single component exports, we could start consuming just the components that are compatible with React 17 and avoid the ones that aren't.

**Comment by willmcvay** [comment]
> I believe the main blocker for us is our extensive use of MUI v4 components. These still make up the bulk of our React-based UI for Console Cloud. If we _can't_ migrate the MUI v4 UI, and our AngularJS UI, to Elements, we'll be rewriting our front end twice:
> 
> 1. Replacing AngularJS and MUI v4 with our react-ui-core component library (which is MUI v5 based); then
> 2. Replacing react-ui-core with Elements.
> 
> In addition to the cost of those two migrations, we'd also be investing in react-ui-core to keep it up-to-date with the Design System which would obviously duplicate much of the effort invested into Elements itself.
> 
> Overall, I think it would be considerably cheaper long-term for the business if we can enable Console Cloud to leverage Elements now instead of later. Happy to dig into this more with you via a different channel if you'd prefer. I can also do some additional investigation on our end to confirm whether MUI v4 is the only blocker for our React 18 upgrade or if there are other dependencies that aren't compatible.

Let's catch up separately - I think it's a solvable problem, we just need to work out a plan and maybe do some investigations.

**Comment by willmcvay** [comment]
As discussed with @kurtdoherty will investigate reverting to v17 on the beta channel only to facilitate migration to v18 - assuming no major blockers, the beta channel will compile with React 17. At the conclusion of the beta, will move to v18 ahead of a prod release. Will need to polyfill useId and possibly some other features to be removed in the interim.
